Add reference to the published article.
google/RED pull request #1
Opened 2018-03-27 08:18 UTC by mpoullet

2018-03-27 08:20 UTC, mpoullet commented
I signed it!

2018-03-27 17:13 UTC, sungjoonchoi requested changes

2018-03-27 17:13 UTC, sungjoonchoi commented on README.md
> +Y. Romano, M. Elad, and P. Milanfar, "[The Little Engine that Could: Regularization by Denoising (RED)](https://epubs.siam.org/doi/10.1137/16M1102884)", SIAM Journal on Imaging Sciences, 10(4), 1804–
Please break the line.

2018-03-28 09:35 UTC, mpoullet commented
Line breaked.

2018-03-28 19:20 UTC, sungjoonchoi approved these changes

2018-03-28 19:20 UTC, sungjoonchoi commented
Looks good! Thanks for your changes.

2018-03-28 19:20 UTC, merged